### PR TITLE
Replace sklearn with scikit-learn

### PR DESCRIPTION
**Pull request by guyrosin**
sklearn was deprecated (see https://pypi.org/project/sklearn/).

Thanks for this library!

### CODE REVIEW

**Comment by jhornas** [comment]
Please repair it :)

**Comment by Martin20494** [comment]
Hello, do you know where I can install the new version with this being replaced with scikit-learn? As currently I could not install due to this issue.

**Comment by guyrosin** [comment]
@Martin20494 yeah you can just install it from source while making the change suggested in this PR to replace sklearn. (git pull -> manually make the change in setup.py -> pip install -e)

**Comment by wuwenglei** [comment]
Hello, thanks for the pull request! The package has been updated on PyPI accordingly.

**Pull request merged**
